### ISSUE TITLE
Change user specific names to $USER

### ISSUE THREAD

**Issue by donadigo** [gabdub/gpie-remote#1]
I think you forgot to change your personal user name to $USER one ;)

E.g:
sudo -u gabriel /home/gabriel/webscripts/dowebcmd.sh "$QUERY_STRING"

**Comment by gabdub** [comment]
This script is run from Apache using the "www-data" user.
You must change "gabriel" with your user name to be sure the user is set correctly.

**Comment by donadigo** [comment]
Ahh then sorry for reporting.
